# CI for Product Catalogs

name: Product Catalog CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup GO 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog-service main.go

      - name: Run Tests
        run: |
          cd src/product-catalog
          go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Lint Checks
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
          golangci-lint run src/product-catalog/...

  Docker-Build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Docker Install
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Verify files
        run: |
          pwd
          ls -R
          ls -l src/product-catalog

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./src/product-catalog
          file: ./src/product-catalog/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{ github.run_number }}

  Update-K8s-Manifest:
    runs-on: ubuntu-latest
    needs: [build, code-quality, Docker-Build]

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update K8s Manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{ github.run_number }}|" kubernetes/productcatalog/deploy.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "shalin-cloud-devops"
          git config --global user.email "shalin.citi.devops@gmail.com"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "Update K8s manifest with new Docker image tag"
          git push origin main
